id: PFF984DA1
initial_creation_type: input
source_metadata:
  title: Getse Mahāpaṇḍita Series
  language: bo
  description: 'Texts by and about Getse Mahāpaṇḍita Gyurme Tsewang Chokdrup (‘gyur
    med tshe dbang mchog grub, 1761–1829) of Katok:'
  volume:
    5136a34c216d417f86d32282aaf1368f:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
created_at: '2022-02-28T23:24:07.200087'
last_modified_at: '2022-02-28T23:24:07.200090'
