name: Quality Check

on:
  push:
    branches: [ master ]
    paths:
      - '**.txt'
      - '**check_quality.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpecha
          
      - name: Perform Quality Check
        run: openpecha qc $(pwd) --save
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Quality Check Run
          
